### ISSUE TITLE
Actividad 3: cuadro comparativo 

### ISSUE THREAD

**Issue by MarleneRamirez0731** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-MarleneRamirez0731#1]
Marlene Maricela Osorio Ramírez 1° BS 
Actividad 3: cuadro comparativo 

![20220901_171254_0000](https://user-images.githubusercontent.com/112357070/188021953-f2f714b7-1a2d-4988-b301-3f36fd674393.png)

**Comment by josealfredo79** [comment]
Es un cuadro comparativo...se debe volver hacer el trabajo...por favor

**Comment by gilbertovelasco1** [comment]
Para mí está muy bien 👌

**Comment by josealfredo79** [comment]
No se realizo el trabajo...nuevamente se insiste

**Comment by MarleneRamirez0731** [comment]
Marlene Maricela Osorio Ramírez
Cuadro comparativo 

[pdf_20220914_143134_0000.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-MarleneRamirez0731/files/9569377/pdf_20220914_143134_0000.pdf)

**Comment by gilbertovelasco1** [comment]
16%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
